Problem statement
Given a 2D list, create a numpy 2D array using it.

Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Print the Numpy array.

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Problem statement
Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.

Print the elements of array.

In [5]:
a = np.full((10),0)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [7]:
a = np.arange(9,50)
print(a)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
a = np.eye(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Problem statement
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.

Note:Array elements are the points where cut is to be made and round upto 2 decimal place.

Print the array element.

In [22]:
a = np.arange(1,9) *(5/9)
a = np.round(a,2)
print(a)

[0.56 1.11 1.67 2.22 2.78 3.33 3.89 4.44]
